name: Auto Close Issue

on:
  workflow_dispatch:
    inputs:
      os:
        default: "['ubuntu-latest', 'windows-latest', 'macos-latest']"

jobs:
  job2:
    strategy:
      matrix:
        os: ${{ fromJSON(inputs.os) }}
    runs-on: ${{ matrix.os }}
    steps:
      - run: echo "Matrix - Project TEST"
