name: Bump Version

on:
  workflow_dispatch:
    inputs:
      scenario:
        description: "scenario"
        required: true
        type: string
        default: "forge, builder"
      type:
        description: "type"
        required: true
        type: choice
        options:
          - "esm"
          - "cjs"
          - "*"

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  define-target-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: gen-build
        uses: actions/github-script@v7
        with:
          result-encoding: string
          script: |
            const { generateBuildCommand } = await import('${{ github.workspace }}/scripts/ci-utils.js')

            return await generateBuildCommand(${{inputs.scenario}}, ${{inputs.type}})

      - id: gen-test
        uses: actions/github-script@v7
        with:
          result-encoding: string
          script: |
            const { generateTestCommand } = await import('${{ github.workspace }}/scripts/ci-utils.js')

            return await generateTestCommand(${{inputs.scenario}}, ${{inputs.type}})

      - id: result
        env:
          E2E_BUILD: ${{steps.gen-build.outputs.result}}
          E2E_TEST: ${{steps.gen-test.outputs.result}}
        run: |
          echo ${E2E_BUILD}
          echo ${E2E_TEST}
