name: CI
on:
  # issue_comment:
  #   types:
  #     - created
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  # workflow_call:

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GH_EMAIL: "41898282+github-actions[bot]@users.noreply.github.com"
  GH_USER: "github-actions[bot]"

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - id: pre-check
        uses: mato533/cicd-actions/pre-check@main

      - env:
          IS_SKIP: ${{ steps.pre-check.outputs.is-skip}}
        run: |
          if [ ${IS_SKIP} > 0 ]; then
            exit 0
          fi

      - name: Install pnpm
        uses: pnpm/action-setup@v4.0.0

      - name: Setup node (20.x)
        uses: actions/setup-node@v4
        with:
          node-version: 20
          #cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: check env
        run: ls -la


        
      - uses: mato533/cicd-actions/format-source-code@develop
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}
          branch: ${{ github.head_ref }}

  test:
    # add comment of pull request && comment is KEYWORD
    # if: (github.event.issue.pull_request != null) && github.event.comment.body == '/run-test'
    name: Run CI
    uses: ./.github/workflows/test.yml
