name: CI
on:
  # issue_comment:
  #   types:
  #     - created
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  # workflow_call:


concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    # add comment of pull request && comment is KEYWORD
    # if: (github.event.issue.pull_request != null) && github.event.comment.body == '/run-test'
    runs-on: ubuntu-latest
    steps:

      - name: check log
        run: |
          git log --pretty=format:"%h - %an, %ar : %s" |head -n 10


      - name: Run CI
        uses: ./.github/workflows/test.yml
