name: Check for pull request
run-name: "Action test"
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  


env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GH_EMAIL: '41898282+github-actions[bot]@users.noreply.github.com'
  GH_USER: 'github-actions[bot]'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: mato533/cicd-actions/pre-check@develop
        id: pre-check
        with:
          target-sha: ${{ github.event.pull_request.head.sha }}
      
      - run: |
          echo "Result"
          echo ${{ steps.pre-check.outputs.is-skip }}