name: Release
on:
  push:
    branches:
      - 'release/**'
jobs:
  test:
    name: Test1
    runs-on: ubuntu-latest
    if: github.event.created
    steps:
      - name: Test
        run: echo test
