name: workflow_dispatch sample 1

on:
  workflow_dispatch:

jobs:
  printLog:
    runs-on: ubuntu-latest

    steps:
      - name: test
        run: |
          echo 1.====
          echo 'Update package.json' |grep '[AUTO]'
          echo 1.====
          echo 'Update package.json' |grep '\[AUTO\]'