name: Execute Test
run-name: TEST EXEC
on:
  workflow_call:

  push:
    branches:
      - main
    paths:
      - '*'
      - src/**
      - '!**.md'

jobs:
  test:
    name: Test1
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: cat file
        run: cat test.txt

      - name: Git
        run: |
          echo '1' $GITHUB_REF
          echo '2' ${{ github.ref }}
          echo '3' ${{ github.ref_name }}
          echo '4' ${{ github.head_ref }} 
          echo '5' ${{ github.base_ref }}
