name: Wip check
on:
  workflow_call:
    outputs:
      is_wip:
        description: "The first output string"
        value: ${{ jobs.check_wip.outputs.is_wip }}

jobs:
  check_wip:
    name: Check wip
    runs-on: ubuntu-latest
    outputs:
      is_wip: ${{ steps.check_wip.outputs.is_wip }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
      
      - name: Check
        id: check_wip
        run: |
          msg="$(git show ${{ github.event.pull_request.head.sha }} -s --format=%B|head -n 1|grep 'wip:' |wc -l )"
          echo "is_wip=${msg}">>"${GITHUB_OUTPUT}"